### ISSUE TITLE
Wrong sign on divu(ueint) and pdivu ?

### ISSUE THREAD

**Issue by marchdf** [AMReX-Fluids/CAMR#67]
I think that the line here: https://github.com/AMReX-Fluids/CAMR/blob/development/Source/Hydro/Hydro_utils_eb_K.H#L107 
should be: `divu(i,j,k,UEINT) -= pdivu;`. And similarly for this line: https://github.com/AMReX-Fluids/CAMR/blob/development/Source/Hydro/Hydro_utils_eb_K.H#L156, it should be `divu(i,j,k,UEINT) -= ...` . And similarly for the 3D version in that function (4 spots total).

This would make things consistent with the non-EB version: https://github.com/AMReX-Fluids/CAMR/blob/6062c91c0ce93c9e2cabea2829f6b43a9749006c/Source/Hydro/Hydro_utils_K.H#L256

The reason for an issue vs a opening a PR is that I am not 100% sure because it seems to make no difference when I run the shock-cylinder case. Thoughts @asalmgren ?

**Comment by jbbel** [comment]
Marc, i have looked over the code and i believe you are correct.  go ahead and submit a PR.  this only does something when equation for total energy gives bad results.  It may well never be used in a shock-cylinder case.  Usually associated with hypersonic stuff from astrophysics or cosmology

**Comment by marchdf** [comment]
Thanks, John. I fixed it (and a couple others) in #66
